dataflow_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      port: 5432
      dbname: dataflow_db
      user: zafff
      password: dataflow123
      schema: staging
      threads: 4