version: "3.9"

services:

  db:
    image: postgres:15
    container_name: dataflow-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dataflow-pipeline
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "-m", "extract.generator"]

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.11
    container_name: dataflow-dbt
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app/dbt
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt
    command: ["dbt", "run"]

  ge:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dataflow-ge
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "-m", "great_expectations.cli"]

volumes:
  postgres_data: